language: python
matrix:
  include:
    - python: 2.7
      env: TEST_MODE=PEP8
    - python: 2.7
      env: TF_VERSION=1.1.0
    - python: 2.7
      env: TF_VERSION=1.2.0
    - python: 2.7
      env: TF_VERSION=1.3.0
    - python: 2.7
      env: TF_VERSION=1.4.0
    - python: 2.7
      env: TF_VERSION=1.5.0
    - python: 2.7
      env: TF_VERSION=1.6.0
    - python: 2.7
      env: TF_VERSION=1.7.0
    - python: 2.7
      env: TF_VERSION=1.8.0
    - python: 2.7
    - python: 3.6
      env: TF_VERSION=1.1.0
    - python: 3.6
notifications:
  email: false
# Adapted from
# https://conda.io/docs/user-guide/tasks/use-conda-with-travis-ci.html
install:
  - sudo apt-get update
  - pip install --only-binary=numpy,scipy numpy scipy opencv-python cython pytest pytest-pep8

  - pip install .
  - if [ -z "$TF_VERSION" ]; then
      pip install tensorflow;
    else
      pip install tensorflow==$TF_VERSION;
    fi

  # Ignore warnings
  - export TF16=$(python -c "from tensornets.utils import tf_later_than; print(tf_later_than('1.6.0'))")
  - if [[ $TF16 == "False" ]]; then
      echo 'filterwarnings =' >> pytest.ini;
      echo '    ignore::DeprecationWarning' >> pytest.ini;
      echo '    ignore::PendingDeprecationWarning' >> pytest.ini;
    fi

  # Detect whether core files are changed or not
  - export CORE_CHANGED=True;
  - for entry in `git diff --name-only HEAD~1`; do if [[ "$entry" == "README.md" ]]; then export CORE_CHANGED=False; fi; done
  - export NUM_CHANGED=$(git diff --name-only HEAD~1 | wc -l);
  - if [ $NUM_CHANGED -gt 1 ]; then CORE_CHANGED=True; fi

  # Detect one of markdown files is changed or not
  - export DOC_ONLY_CHANGED=False;
  - if [ $NUM_CHANGED == 1 ] && [[ "$(git diff --name-only HEAD~1)" == *"md" ]]; then
      export DOC_ONLY_CHANGED=True;
    fi

script:
  - if [[ "$DOC_ONLY_CHANGED" == "False" ]]; then
      if [[ "$TEST_MODE" == "PEP8" ]]; then
         PYTHONPATH=$PWD:$PYTHONPATH py.test --pep8 -m pep8;
      else
         PYTHONPATH=$PWD:$PYTHONPATH py.test tests/ --verbose --ignore=tests/all*;
      fi;
    fi
